export const cartTypes = {
    CART_ITEM_UP: 'CART_ITEM_UP',
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DECREASE_ITEM_BY_ID: 'DECREASE_ITEM_BY_ID'
}